# Generated by Django 4.1.6 on 2023-02-14 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_genre_playlist_trackgenre_playlistuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=75, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=75, null=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('deleted_by', models.CharField(max_length=75, null=True)),
                ('track_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.track')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=75, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=75, null=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('deleted_by', models.CharField(max_length=75, null=True)),
                ('artist_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=75, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=75, null=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('deleted_by', models.CharField(max_length=75, null=True)),
                ('track_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.track')),
            ],
        ),
    ]
