# Generated by Django 4.1.6 on 2023-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_saved_follower_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
